language: r

sudo: required

env: _R_CHECK_CRAN_INCOMING_=FALSE

r_packages:
<<<<<<< HEAD
- covr
=======
  - covr
>>>>>>> deployment/master
- devtools

after_success:
  - Rscript -e 'library(covr); codecov()'
