# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

pool:
  vmImage: 'ubuntu-latest'

container: 'rocker/tidyverse:latest'

steps:
- script: Rscript -e 'sessionInfo()'
  displayName: 'R Version'

- script: sudo Rscript -e 'install.packages("huxtable"); devtools::check()'
  displayName: 'Package Check'
